### PR TITLE
Fixes #34

### LINKED ISSUE #34: dotnet watch, dotnet run crashes if aspx file is changed
Tried the following on macOS.

Steps to reproduce:
- Enable dynamic compilation
- Run the sample project (samples/SystemWebUISample) using `dotnet watch` or `dotnet run`
- Save dynamic_page.aspx
- `dotnet watch` throws the following errors:
```
dotnet watch ❌ Exited with error code 139
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
```
- `dotnet run` stops running and returns to prompt.

If I comment the following line in WebFormsCompilationService.cs `dotnet run` refreshes (doesn't crash). You have to refresh the browser to see the changes. `dotnet watch` continues to crash:

```cs
using (_routes.GetWriteLock()) // in UpdateTypesAsync method
```

### PR DESCRIPTION
**Pull request by Code-DJ**
Fixes #34

### CODE REVIEW

**Comment by Code-DJ** [comment]
> @Code-DJ are you still going to work on this pr?

No, I was waiting on some guidance from you on the comments above.

**Comment by twsouthwick** [comment]
It was marked as a draft so I haven't reviewed it. When you're ready for a review, swap the draft off

**Comment by twsouthwick** [comment]
> I was waiting on some guidance from you on the comments above.

I'm not sure which comments you're referring to

**Comment by Code-DJ** [comment]
> > I was waiting on some guidance from you on the comments above.
> 
> I'm not sure which comments you're referring to

I put the following comment against each of these files.

`src/Compiler.Dynamic/WebFormsCompilationService.cs` line 170:
> @twsouthwick can you help with this - we want all aspx pages to only process the first time. After that the above dependencies logic will/should click in.

> Is this assumption correct? can we use static readonly List<string> or do we need to worry about concurrency/thread safety?

`src/Compiler.Dynamic/WebFormsCompilationService.cs` line 177:
> I am not sure about this - dependencies.SelectMany(s => s.Value).Distinct(); is getting all pages causing the page assemblies to get unloaded. Then, if you navigate to any of those pages, the page doesn't load.

> I have used temporary logic Enumerable.Empty<Timed<ICompiledPage>>(); to prevent unloading but given that changes is being handled, what is deletions supposed to handle?


`src/WebForms/VirtualPath.cs` line 99:
> If you are on lets say dynamic_page.aspx in the browser, if you modify and save the file in any editor, we get an error file is in use by another process, hence, changed to use FileStream.

**Comment by twsouthwick** [comment]
weird - I don't see any comments. I've reworked the compilation to await each page so they can depend on each other in #94. Feel free to rebase your fix on that

**Comment by Code-DJ** [comment]
Closing since #94 has reworked compilation.

**Comment by twsouthwick** [comment]
sounds good. please let me know if you try it out and if it works/doesn't work

**Pull request closed without merging**
