### PR TITLE
Add a source generator to use C# 12 interceptors

### PR DESCRIPTION
**Pull request by twsouthwick**
This will create an auto-generated, strongly-typed, method to register all the routes. Although we don't currently support AOT, this at least makes it so we don't need to use reflection to load up the pages if opted into.

This change will also make it easier to set up some automated testing of the samples as they will be published and can be run independently of the repo.

### CODE REVIEW

**Comment by twsouthwick** [comment]
Dependent on:

- [ ] #101

**Comment by twsouthwick** [comment]
@birojnayak I'm going to go ahead and merge this in - I'll watch for feedback on it, but we can address any thoughts in subsequent prs

**Comment by birojnayak** [comment]
@twsouthwick it's ok.. I am not able to keep up the speed you are publishing PR :).. I will try my best whenever I can..

**Comment by twsouthwick** [comment]
Yeah, I've had some time this weekend and got going on enabling a number of things :)

**Pull request merged**
